name: cooking
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - fastapi
  - uvicorn
  - sqlalchemy
  - alembic
  - pydantic-settings
  - python-multipart
  - itsdangerous
  - pillow
  - pip
